import skfuzzy as fuzz
from skfuzzy import control as ctrl

import numpy as np

#INPUTAN
pelayanan = ctrl.Antecedent(np.arange(50,100),'pelayanan')
pelayanan['rendah'] = fuzz.trapmf(pelayanan.universe, [50,50,86,91])
pelayanan['sedang'] = fuzz.trimf(pelayanan.universe, [86,91,97])
pelayanan['tinggi'] = fuzz.trapmf(pelayanan.universe, [91,97,100,100])

sanitasi = ctrl.Antecedent(np.arange(25,100),'sanitasi')
sanitasi['rendah'] = fuzz.trapmf(sanitasi.universe, [25,25,91,95])
sanitasi['sedang'] = fuzz.trimf(sanitasi.universe, [91,95,99])
sanitasi['tinggi'] = fuzz.trapmf(sanitasi.universe, [95,99,100,100])

desa = ctrl.Antecedent(np.arange(40,100),'desa')
desa['rendah'] = fuzz.trapmf(desa.universe, [40,40,88,93])
desa['sedang'] = fuzz.trimf(desa.universe, [88,93,98])
desa['tinggi'] = fuzz.trapmf(desa.universe, [93,98,100,100])

asi = ctrl.Antecedent(np.arange(40,100),'asi')
asi['rendah'] = fuzz.trapmf(asi.universe, [40,40,68,78])
asi['sedang'] = fuzz.trimf(asi.universe, [68,78,88])
asi['tinggi'] = fuzz.trapmf(asi.universe, [78,88,100,100])

stunting = ctrl.Antecedent(np.arange(5,50),'stunting')
stunting['rendah'] = fuzz.trapmf(stunting.universe, [5,5,8,14])
stunting['sedang'] = fuzz.trimf(stunting.universe, [8,14,20])
stunting['tinggi'] = fuzz.trapmf(stunting.universe, [14,20,50,50])

# pelayanan.view()
# sanitasi.view()
# desa.view()
# asi.view()
# stunting.view()

#OUTPUT
risiko = ctrl.Consequent(np.arange(0,5),'risiko')
risiko['rendah'] = fuzz.trimf(risiko.universe, [0,1,2])
risiko['sedang'] = fuzz.trimf(risiko.universe, [1,2,3])
risiko['tinggi'] = fuzz.trimf(risiko.universe, [2,3,4])

#risiko.view()


#rule
rule1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule2 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule3 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule4 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule5 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['tinggi'])
rule6 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule7 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['tinggi'])
rule8 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule9 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule10 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule11 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule12 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule13 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule13_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule14 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule15 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule16 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule16_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['tinggi'])
rule17 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule17_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule18 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule19 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule20 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule22 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule21 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule21_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule23 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule23_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['tinggi'])
rule24 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule25 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule26 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule26_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule27 = ctrl.Rule(pelayanan['rendah'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule28 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule29 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule30 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule31 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule31_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule32 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule33 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule34 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule34_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['tinggi'])
rule35 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule35_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule36 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule37 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule37_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule38 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule39 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule40 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule41 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule42 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule43 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule43_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['sedang'])
rule44 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule45 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])
rule45_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule46 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule46_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule47 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule47_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule48 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule49 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule49_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule50 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule51 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule51_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule52 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule53 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule53_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule54 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])
rule54_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule55 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule56 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule57 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule58 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule58_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule59 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule59_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['tinggi'])
rule60 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule61 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['tinggi'])
rule62 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule62_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule63 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule64 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule64_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule65 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule65_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule66 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule67 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule67_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule68 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule69 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule69_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule70 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule71 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule71_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule72 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])
rule72_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule73 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule74 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule74_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule75 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule76 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule77 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['rendah'])
rule77_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule78 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule78_1 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule79 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule80 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule81 = ctrl.Rule(pelayanan['rendah'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule82 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule83 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule84 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule85 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule85_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule86 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule87 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule87_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule88 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule88_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['tinggi'])
rule89 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule89_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])
rule90 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule91 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule91_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule92 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule93 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['sedang'])
rule93_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule94 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule95 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule96 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule97 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule97_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['sedang'])
rule98 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule99 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])
rule99_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule100 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule100_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule101 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule101_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule102 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule103 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule103_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule104 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule105 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule105_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule106 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule107 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule107_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule108 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])
rule108_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule109 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule109_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule110 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule111 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule112 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule113 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule114 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule115 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule115_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['sedang'])
rule116 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule117 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])
rule117_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule118 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule119 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule120 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['sedang'])
rule121 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule122 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule123 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule124 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['sedang'])
rule125 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule126 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])

rule127 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule128 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule129 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['sedang'])
rule130 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule131 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule132 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule133 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule134 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule135 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule127_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule129_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule135_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])

rule136 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule137 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule138 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule139 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule140 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule141 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule142 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule143 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule144 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule136_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule137_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule139_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule141_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule143_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule144_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule145 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule146 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule147 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['sedang'])
rule148 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule149 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule150 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule151 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule152 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule153 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule145_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule147_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule153_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])

rule154 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule155 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule156 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['rendah'])
rule157 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule158 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule159 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule160 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule161 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule162 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule155_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule156_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule159_1 = ctrl.Rule(pelayanan['sedang'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])

rule163 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule164 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule165 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule166 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule167 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule168 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule169 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule170 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule171 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule166_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['tinggi'])
rule167_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['tinggi'])
rule170_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['tinggi'])

rule172 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule173 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule174 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule175 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule176 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule177 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule178 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule179 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule180 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule172_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule173_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule175_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule177_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule179_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])

rule180 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])
rule181 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule182 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule183 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule184 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule185 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['rendah'])
rule186 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule187 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule188 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule189 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule180_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])
rule182_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule185_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule186_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['rendah'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])

rule190 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule191 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule192 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule193 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule194 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule195 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule196 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule197 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule198 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule190_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['tinggi'])
rule191_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule193_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule195_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])
rule197_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule198_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['tinggi'])

rule199 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule200 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule201 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['sedang'])
rule202 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['sedang'])
rule203 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule204 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])
rule205 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule206 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['sedang'])
rule207 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule199_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['sedang'])
rule201_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule207_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['sedang'])

rule208 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule209 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule210 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['rendah'])
rule211 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule212 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule213 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule214 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule215 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule216 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule209_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule210_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule213_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['sedang'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])

rule217 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule218 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule219 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule220 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule221 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['rendah'])
rule222 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule223 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule224 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule225 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule218_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['rendah'] & stunting['sedang'], risiko['tinggi'])
rule221_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule222_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['rendah'] & asi['sedang'] & stunting['tinggi'], risiko['tinggi'])

rule226 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule227 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule228 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['rendah'])
rule229 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule230 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['sedang'], risiko['sedang'])
rule231 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule232 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule233 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule234 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

rule227_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['sedang'], risiko['sedang'])
rule228_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['rendah'] & stunting['tinggi'], risiko['tinggi'])
rule231_1 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['sedang'] & asi['sedang'] & stunting['tinggi'], risiko['sedang'])

rule235 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['rendah'], risiko['rendah'])
rule236 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['sedang'], risiko['rendah'])
rule237 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['rendah'] & stunting['tinggi'], risiko['rendah'])
rule238 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['rendah'], risiko['rendah'])
rule239 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['sedang'], risiko['rendah'])
rule240 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['sedang'] & stunting['tinggi'], risiko['rendah'])
rule241 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['rendah'], risiko['rendah'])
rule242 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['sedang'], risiko['rendah'])
rule243 = ctrl.Rule(pelayanan['tinggi'] & sanitasi['tinggi'] & desa['tinggi'] & asi['tinggi'] & stunting['tinggi'], risiko['rendah'])

risiko_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9,rule10,rule11,rule12,rule13,rule14,rule15,rule16,rule17,rule18,rule19,rule20,
                                  rule21,rule22,rule23,rule24,rule25,rule26,rule27,rule28,rule29,rule30,rule31,rule32,rule33,rule34,rule35,rule36,rule37,rule38,rule39,rule40,
                                  rule41,rule42,rule43,rule44,rule45,rule46,rule47,rule48,rule49,rule50,rule51,rule52,rule53,rule54,rule55,rule56,rule57,rule58,rule59,rule60,
                                  rule61,rule62,rule63,rule64,rule65,rule66,rule67,rule68,rule69,rule70,rule71,rule72,rule73,rule74,rule75,rule76,rule77,rule78,rule79,rule80,
                                  rule81,rule82,rule83,rule84,rule85,rule86,rule87,rule88,rule89,rule90,rule91,rule92,rule93,rule94,rule95,rule96,rule97,rule98,rule99,rule100,
                                  rule101,rule102,rule103,rule104,rule105,rule106,rule107,rule108,rule109,rule110,rule111,rule112,rule113,rule114,rule115,rule116,rule117,rule118,rule119,rule120,
                                  rule121,rule122,rule123,rule124,rule125,rule126,rule127,rule128,rule129,rule130,rule131,rule132,rule133,rule134,rule135,rule136,rule137,rule138,rule139,rule140,
                                  rule141,rule142,rule143,rule144,rule145,rule146,rule147,rule148,rule149,rule150,rule151,rule152,rule153,rule154,rule155,rule156,rule157,rule158,rule159,rule160,
                                  rule161,rule162,rule163,rule164,rule165,rule166,rule167,rule168,rule169,rule170,rule171,rule172,rule173,rule174,rule175,rule176,rule177,rule178,rule179,rule180,
                                  rule181,rule182,rule183,rule184,rule185,rule186,rule187,rule188,rule189,rule190,rule191,rule192,rule193,rule194,rule195,rule196,rule197,rule198,rule199,rule200,
                                  rule201,rule102,rule203,rule204,rule205,rule206,rule207,rule208,rule209,rule210,rule111,rule212,rule213,rule214,rule215,rule216,rule217,rule218,rule219,rule220,
                                  rule221,rule222,rule223,rule224,rule225,rule226,rule227,rule228,rule229,rule230,rule231,rule232,rule233,rule234,rule235,rule236,rule237,rule238,rule239,rule240,
                                  rule241,rule242,rule243,
                                  rule13_1,rule16_1,rule17_1,rule21_1,rule23_1,rule26_1,rule31_1,rule34_1,rule35_1,rule37_1,rule43_1,rule45_1,rule46_1,rule47_1,rule49_1,rule51_1,rule53_1,rule54_1,rule58_1,rule59_1,
                                  rule62_1,rule64_1,rule65_1,rule67_1,rule69_1,rule71_1,rule72_1,rule74_1,rule77_1,rule78_1,rule85_1,rule87_1,rule88_1,rule89_1,rule91_1,rule93_1,rule97_1,rule99_1,rule100_1,rule101_1,
                                  rule103_1,rule105_1,rule107_1,rule108_1,rule109_1,rule115_1,rule117_1,rule127_1,rule129_1,rule135_1,rule136_1,rule137_1,rule139_1,rule141_1,rule143_1,rule144_1,rule145_1,rule147_1,rule153_1,rule155_1,
                                  rule156_1,rule159_1,rule166_1,rule167_1,rule170_1,rule172_1,rule173_1,rule175_1,rule177_1,rule179_1,rule180_1,rule182_1,rule185_1,rule186_1,rule190_1,rule191_1,rule193_1,rule195_1,rule197_1,rule198_1,
                                  rule199_1,rule201_1,rule207_1,rule209_1,rule210_1,rule213_1,rule218_1,rule221_1,rule222_1,rule227_1,rule228_1,rule231_1,])

tipping = ctrl.ControlSystemSimulation(risiko_ctrl)